server:
  port: 8080

spring:
  application:
    name: restoran
  data:
    jpa.repositories.enabled: true
  datasource:
    url: jdbc:postgresql://postgres-restoran:5432/restoran
    username: restoran
    password: restoran
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 10000
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        jdbc:
          lob:
            non-contextual-creation: true
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
